version: 2
jobs:
  build:
    working_directory: ~/mux
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - restore_cache:
          key: v1-node-modules
      - run:
          name: Install npm packages
          command: yarn --pure-lockfile
      - save_cache:
          key: v1-node-modules
          paths:
            - node_modules
      - run:
          name: Run Flow Checks
          command: yarn flow -- check
      - run:
          name: Run Tests
          command: yarn test -- --coverage
      - run:
          name: Upload results to Codecov
          command: bash <(curl -s https://codecov.io/bash)
